services:
#Service odoo toma el Dockerfile de ./odoo
 odoo:
  build: ./odoo
  hostname: odoo
  environment:
  - DBHOST=postgres
  - DBUSER=odoo
  - ODOOUSER=odoo
  - DBPASS=abc123.
  - ADMINPASS=abc123.
  - LOGFILE=/var/log/odoo/odoo.log
  - VERSION=OCB
  ports:
  - "8069:8069"
  - "5678:5678"
  #Mapeo del directorio de la MV en el container
  volumes:
  - ~/odoo/src:/opt/odoo/src
